In [1]:
import pandas as pd
import numpy as np

In [2]:
ar = np.array([0, 1, 2, 3])
ar

array([0, 1, 2, 3])

In [3]:
ar1 = np.array([0, 1, None, 3])
ar1

array([0, 1, None, 3], dtype=object)

In [4]:
ar.mean()

1.5

In [5]:
ar1.mean()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [6]:
ar2 = np.array([0, 1, np.nan, 3])
ar2

array([ 0.,  1., nan,  3.])

In [7]:
ar2.mean()

nan

In [8]:
np.nanmean(ar2)

1.3333333333333333

In [9]:
ser2 = pd.Series([np.nan, 'Bonjour',2, None])

In [10]:
ser2 + ser2

0               NaN
1    BonjourBonjour
2                 4
3               NaN
dtype: object

In [11]:
ser2.isnull()

0     True
1    False
2    False
3     True
dtype: bool

In [12]:
ser2.notnull()

0    False
1     True
2     True
3    False
dtype: bool

In [13]:
ser2[ser2.notnull()]

1    Bonjour
2          2
dtype: object

In [14]:
ser2.dropna()

1    Bonjour
2          2
dtype: object

In [15]:
ser2.fillna(0)

0          0
1    Bonjour
2          2
3          0
dtype: object

In [16]:
df1=pd.DataFrame([[1, np.nan, 3], [4, 5, 6], [np.nan, 8, 9]])
df1

0    1  2
0  1.0  NaN  3
1  4.0  5.0  6
2  NaN  8.0  9

In [17]:
df1.dropna()

0    1  2
1  4.0  5.0  6

In [18]:
df1.dropna(axis=1)

2
0  3
1  6
2  9

In [19]:
df1.fillna(0)

0    1  2
0  1.0  0.0  3
1  4.0  5.0  6
2  0.0  8.0  9

In [20]:
df1.fillna({0:'Abs',1:99})

0     1  2
0    1  99.0  3
1    4   5.0  6
2  Abs   8.0  9